#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xset
Version  : 1.2.4
Release  : 2
URL      : https://www.x.org/releases/individual/app/xset-1.2.4.tar.gz
Source0  : https://www.x.org/releases/individual/app/xset-1.2.4.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xset-bin
Requires: xset-license
Requires: xset-man
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
BuildRequires : pkgconfig(xxf86misc)

%description
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xset package.
Group: Binaries
Requires: xset-license
Requires: xset-man

%description bin
bin components for the xset package.


%package license
Summary: license components for the xset package.
Group: Default

%description license
license components for the xset package.


%package man
Summary: man components for the xset package.
Group: Default

%description man
man components for the xset package.


%prep
%setup -q -n xset-1.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532031242
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1532031242
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/xset
cp COPYING %{buildroot}/usr/share/doc/xset/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xset

%files license
%defattr(-,root,root,-)
/usr/share/doc/xset/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/xset.1
