#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xset
Version  : 1.2.4
Release  : 6
URL      : https://www.x.org/releases/individual/app/xset-1.2.4.tar.gz
Source0  : https://www.x.org/releases/individual/app/xset-1.2.4.tar.gz
Source1  : https://www.x.org/releases/individual/app/xset-1.2.4.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xset-bin = %{version}-%{release}
Requires: xset-license = %{version}-%{release}
Requires: xset-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
All questions regarding this software should be directed at the
Xorg mailing list:

%package bin
Summary: bin components for the xset package.
Group: Binaries
Requires: xset-license = %{version}-%{release}

%description bin
bin components for the xset package.


%package license
Summary: license components for the xset package.
Group: Default

%description license
license components for the xset package.


%package man
Summary: man components for the xset package.
Group: Default

%description man
man components for the xset package.


%prep
%setup -q -n xset-1.2.4
cd %{_builddir}/xset-1.2.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614192465
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1614192465
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xset
cp %{_builddir}/xset-1.2.4/COPYING %{buildroot}/usr/share/package-licenses/xset/e329518edc3fad9042360d8b6d7b8fcd5097d012
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xset

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xset/e329518edc3fad9042360d8b6d7b8fcd5097d012

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xset.1
